excelPath: "C:\\Users\\tmkein\\Documents\\docs\\Trainingstagebuch.xls"
server:
      applicationConnectors:
      - type: http
        port: 9000
      adminConnectors:
      - type: http
        port: 9001